/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLogbookRouteImport } from './routes/app.logbook'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppItEquipmentRouteImport } from './routes/app.it-equipment'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCourseProgressRouteImport } from './routes/app.course-progress'
import { Route as AppCourseMaterialsRouteImport } from './routes/app.course-materials'
import { Route as AppConflictsRouteImport } from './routes/app.conflicts'
import { Route as AppConfigRouteImport } from './routes/app.config'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppCancellationsRouteImport } from './routes/app.cancellations'
import { Route as AppBusRouteImport } from './routes/app.bus'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLogbookRoute = AppLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppItEquipmentRoute = AppItEquipmentRouteImport.update({
  id: '/it-equipment',
  path: '/it-equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCourseProgressRoute = AppCourseProgressRouteImport.update({
  id: '/course-progress',
  path: '/course-progress',
  getParentRoute: () => AppRoute,
} as any)
const AppCourseMaterialsRoute = AppCourseMaterialsRouteImport.update({
  id: '/course-materials',
  path: '/course-materials',
  getParentRoute: () => AppRoute,
} as any)
const AppConflictsRoute = AppConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCancellationsRoute = AppCancellationsRouteImport.update({
  id: '/cancellations',
  path: '/cancellations',
  getParentRoute: () => AppRoute,
} as any)
const AppBusRoute = AppBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/bus': typeof AppBusRoute
  '/app/cancellations': typeof AppCancellationsRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/config': typeof AppConfigRoute
  '/app/conflicts': typeof AppConflictsRoute
  '/app/course-materials': typeof AppCourseMaterialsRoute
  '/app/course-progress': typeof AppCourseProgressRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/it-equipment': typeof AppItEquipmentRoute
  '/app/library': typeof AppLibraryRoute
  '/app/logbook': typeof AppLogbookRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/bus': typeof AppBusRoute
  '/app/cancellations': typeof AppCancellationsRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/config': typeof AppConfigRoute
  '/app/conflicts': typeof AppConflictsRoute
  '/app/course-materials': typeof AppCourseMaterialsRoute
  '/app/course-progress': typeof AppCourseProgressRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/it-equipment': typeof AppItEquipmentRoute
  '/app/library': typeof AppLibraryRoute
  '/app/logbook': typeof AppLogbookRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/bus': typeof AppBusRoute
  '/app/cancellations': typeof AppCancellationsRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/config': typeof AppConfigRoute
  '/app/conflicts': typeof AppConflictsRoute
  '/app/course-materials': typeof AppCourseMaterialsRoute
  '/app/course-progress': typeof AppCourseProgressRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/it-equipment': typeof AppItEquipmentRoute
  '/app/library': typeof AppLibraryRoute
  '/app/logbook': typeof AppLogbookRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/results': typeof AppResultsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/announcements'
    | '/app/assets'
    | '/app/audit'
    | '/app/bookings'
    | '/app/bus'
    | '/app/cancellations'
    | '/app/checkout'
    | '/app/config'
    | '/app/conflicts'
    | '/app/course-materials'
    | '/app/course-progress'
    | '/app/dashboard'
    | '/app/it-equipment'
    | '/app/library'
    | '/app/logbook'
    | '/app/profile'
    | '/app/reports'
    | '/app/results'
    | '/app/schedule'
    | '/app/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/announcements'
    | '/app/assets'
    | '/app/audit'
    | '/app/bookings'
    | '/app/bus'
    | '/app/cancellations'
    | '/app/checkout'
    | '/app/config'
    | '/app/conflicts'
    | '/app/course-materials'
    | '/app/course-progress'
    | '/app/dashboard'
    | '/app/it-equipment'
    | '/app/library'
    | '/app/logbook'
    | '/app/profile'
    | '/app/reports'
    | '/app/results'
    | '/app/schedule'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/announcements'
    | '/app/assets'
    | '/app/audit'
    | '/app/bookings'
    | '/app/bus'
    | '/app/cancellations'
    | '/app/checkout'
    | '/app/config'
    | '/app/conflicts'
    | '/app/course-materials'
    | '/app/course-progress'
    | '/app/dashboard'
    | '/app/it-equipment'
    | '/app/library'
    | '/app/logbook'
    | '/app/profile'
    | '/app/reports'
    | '/app/results'
    | '/app/schedule'
    | '/app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logbook': {
      id: '/app/logbook'
      path: '/logbook'
      fullPath: '/app/logbook'
      preLoaderRoute: typeof AppLogbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/it-equipment': {
      id: '/app/it-equipment'
      path: '/it-equipment'
      fullPath: '/app/it-equipment'
      preLoaderRoute: typeof AppItEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/course-progress': {
      id: '/app/course-progress'
      path: '/course-progress'
      fullPath: '/app/course-progress'
      preLoaderRoute: typeof AppCourseProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/course-materials': {
      id: '/app/course-materials'
      path: '/course-materials'
      fullPath: '/app/course-materials'
      preLoaderRoute: typeof AppCourseMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conflicts': {
      id: '/app/conflicts'
      path: '/conflicts'
      fullPath: '/app/conflicts'
      preLoaderRoute: typeof AppConflictsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config': {
      id: '/app/config'
      path: '/config'
      fullPath: '/app/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cancellations': {
      id: '/app/cancellations'
      path: '/cancellations'
      fullPath: '/app/cancellations'
      preLoaderRoute: typeof AppCancellationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bus': {
      id: '/app/bus'
      path: '/bus'
      fullPath: '/app/bus'
      preLoaderRoute: typeof AppBusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppBusRoute: typeof AppBusRoute
  AppCancellationsRoute: typeof AppCancellationsRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppConfigRoute: typeof AppConfigRoute
  AppConflictsRoute: typeof AppConflictsRoute
  AppCourseMaterialsRoute: typeof AppCourseMaterialsRoute
  AppCourseProgressRoute: typeof AppCourseProgressRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppItEquipmentRoute: typeof AppItEquipmentRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppLogbookRoute: typeof AppLogbookRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppBusRoute: AppBusRoute,
  AppCancellationsRoute: AppCancellationsRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppConfigRoute: AppConfigRoute,
  AppConflictsRoute: AppConflictsRoute,
  AppCourseMaterialsRoute: AppCourseMaterialsRoute,
  AppCourseProgressRoute: AppCourseProgressRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppItEquipmentRoute: AppItEquipmentRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppLogbookRoute: AppLogbookRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
